[project]
name = "openai-agents-demo"
version = "0.1.0"
description = "OpenAI Agents integration with LangSmith tracing"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openai>=1.0.0",
    "langsmith[openai-agents]>=0.4.38",
]
